name: panic_of_plastic
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  app_ui:
    path: packages/app_ui
  audioplayers: ^5.2.0
  bloc: ^8.1.2
  cloud_firestore: ^4.15.5
  equatable: ^2.0.5
  file_selector: ^1.0.1
  flame: ^1.10.0
  flame_behaviors: ^1.0.0
  flame_tiled: ^1.15.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.0
  leap:
  logging: ^1.2.0
  ordered_set: ^5.0.2
  path: ^1.8.3
  pathxp: ^0.4.0
  provider: ^6.0.5
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0

dependency_overrides:
  flame_tiled:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: main
      path: packages/flame_tiled
  leap:
    git:
      url: https://github.com/VeryGoodOpenSource/leap.git
      ref: vgv
      path: packages/leap
      
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/map/
    - assets/map/anim/
    - assets/map/objects/
    - assets/music/
    - assets/sfx/
